# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: dynode

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "running black"
    steps: 
    - uses: actions/checkout@v2
    - name: "Set up Python 3"
      uses: actions/setup-python@v2
      with: 
          python-version: '3.x'
    - name: "Install dependencies"
      run: "pip install -r requirements_dev.txt"

  black: 
    runs-on: ubuntu-latest
    name: "running black"
    needs: [build]
    steps:
    - name: "Run black!"
      run: "black --check ."

  pylint: 
    runs-on: ubuntu-latest
    name: "running pylint"
    needs: [build]
    steps: 
    - name: "Run pylint!"
      run: "pylint dynode"

  pytest:
    runs-on: ubuntu-latest
    needs: [build, black, pylint]
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Test with pytest
      run: |
        pytest --cov=dynode --cov-report=xml test
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        file: ./coverage.xml
